config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users, except: [:new, :create, :index]
  resources :friendships
  resources :posts, only: [:destroy] do
    resources :comments, only: [:create]
  end
  resources :likes, only: [:create, :destroy]
  
  root 'static_pages#home'
  post "/", to: "posts#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates :body, presence: true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, as: :likeable
  has_many :comments, as: :commentable

  default_scope -> { order(created_at: :desc ) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  validates :name, presence: true

  has_many :friendships
  has_many :inverse_friends, class_name: "Friendship", foreign_key: :friend_id

  has_many :posts
  has_many :likes
  has_many :comments

  # after_create :send_welcome_mail

  def friends
    friends = friendships.map { |f| f.friend if f.accepted }.compact
    friends + inverse_friends.map { |f| f.user if f.accepted }.compact
  end

  def pending_received
    requests = inverse_friends.map { |f| f.user if !f.accepted }.compact
  end

  def pending_sent
    requests = friendships.map { |f| f.friend if !f.accepted }.compact
  end

  def friends?(user)
    self.friends.include?(user)
  end

  def connection?(user)
    self.friends?(user) || self.pending_received.include?(user) || self.pending_sent.include?(user)
  end

  def feed
    friend_ids = "SELECT friend_id FROM friendships WHERE user_id = :user_id"
    friend_ids + "SELECT user_id FROM friendships WHERE friend_id = :user_id"
    feed = Post.where("user_id IN (#{friend_ids}) OR user_id = :user_id", user_id: id).order(created_at: :desc)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end      
  end

  def send_welcome_mail
    WelcomeMailer.with(user: self).welcome_email.deliver!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || root_path
  end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      flash[:success] = "You commented!"
      redirect_to root_path 
    else
      flash[:alert] = "Something went wrong!"
      redirect_to root_path 
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:body, :commentable_id, :commentable_type)
    end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:destroy, :edit, :update]
  
  def index
    @pending_sent = current_user.pending_sent
    @pending_received = current_user.pending_received
    @users = User.all
  end
  
  def show

  end

  def create
    @friendship = current_user.friendships.build(friend_id: params[:friend_id])
    if @friendship.save
      flash[:success] = "Friend request sent"
      redirect_to root_path
    else
      flash[:alert] = "Error sending friend request"
      redirect_to root_path
    end
  end

  def update
    @friendship.toggle(:accepted)
    if @friendship.save
      flash[:success] = "Friend request accepted"
      redirect_to friendships_path
    else
      flash[:alert] = "Error accepting friend request"
      redirect_to friendships_path
    end
  end

  def destroy
    @friendship.destroy
    flash[:success] = "Friendship destroyed"
    redirect_to friendships_path
  end

  private
  def set_friendship
    @friendship = current_user.friendships.find_by(friend_id: params[:id]) || current_user.inverse_friends.find_by(user_id: params[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.build(likeable_id: params[:id], likeable_type: params[:type])
    if @like.save
      flash[:success] = "You liked something!"
      redirect_to root_path 
    else
      flash[:alert] = "Something went wrong!"
      redirect_to root_path 
    end
  end

  def destroy
    @like = Like.find_by(likeable_id: params[:id], user_id: current_user.id)
    @like.destroy
    flash[:success] = "You unliked something!"
    redirect_to root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post created!"
      redirect_to root_path 
    else
      render "static_pages/home" 
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Post deleted"
    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:user_id, :body)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @post = current_user.posts.build
    @feed_items = current_user.feed
    @comment = Comment.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @feed_items = @user.posts
    @comment = Comment.new
    @friends = @user.friends
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, size: 80 )
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFace2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "Home", root_path %>&nbsp;&nbsp;|&nbsp;&nbsp;
      <%= link_to "Log Out", destroy_user_session_path, method: :delete %>&nbsp;&nbsp;|&nbsp;&nbsp;
      <%= link_to "#{current_user.pending_received.length} Friend Requests", friendships_path %>&nbsp;&nbsp;|&nbsp;&nbsp;
      <%= link_to "Profile", current_user %>
    <% end %>
    <% flash.each do |type, msg| %>
      <p><%= type %>: <%= msg %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_comments.html.erb
<% if commentable.comments.any? %>
  <% commentable.comments.each do |c| %>
    <p><%= gravatar_for(c.user, size: 20) %><%= link_to c.user.name, user_path(c.user) %>: <%= c.body %></p>
  <% end %>
<% end %>

<%= form_for @comment, url: post_comments_path(commentable) do |f| %>
  <%= f.hidden_field :commentable_id, value: commentable.id %>
  <%= f.hidden_field :commentable_type, value: commentable.class.name %>
  <%= f.text_area :body, placeholder: "Comment on this" %>

  <%= f.submit "Comment" %>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <% @feed_items.each do |f| %>
    <div>
      <p><%= gravatar_for(f.user, size: 40) %><%= link_to f.user.name, user_path(f.user) %> said:</p>
      <p><%= f.body %></p>
      <p>Posted <%= time_ago_in_words(f.created_at) %> ago. <%= render "shared/like_button", post: f %></p>
      <p><%= pluralize(f.likes.count, "Like") %></p>
      <%= render "shared/comments", commentable: f %>
      
      <br />
    </div>
  <% end %>
<% end %>

app/views/shared/_friends.html.erb
<% if @friends.empty? %>
  <h3><%= @user.name %> has NO FRIENDS!!</h3>
<% else %>
  <h3><%= @user.name %> has <%= @friends.length %> friends</h3>
  <% @friends.each do |friend| %>
    <p>
      <%= friend[:name] %>
      <%= link_to "View Profile", user_path(friend) %>
      <% if current_user.friends.include?(friend) %>
        <%= link_to "Delete Friend", friendship_path(friend), method: :delete %>
      <% end %>
    </p>
  <% end %>
<% end %>

app/views/shared/_like_button.html.erb
<% if post.likes.find_by(user_id: current_user.id) %>
  <%= link_to "Unlike", like_path(post), method: :delete %>
<% else %>
  <%= link_to "Like", likes_path(id: post.id, type: "Post"), method: :post %>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_for(@post, url: root_path) do |f| %>
  <%= f.text_area(:body, placeholder: "Compose new post...") %>
  <%= f.submit "Post" %>
<% end %>